import React from 'react';
import { HiOutlineHome, HiOutlineBriefcase, HiOutlineDocumentText, HiOutlineStar, HiOutlineBell, HiOutlineCalendar, HiOutlineChatAlt2, HiOutlineCog, HiOutlineLightningBolt, HiOutlineAdjustments, HiOutlineUser, HiOutlineBookmark, HiOutlineMail, HiOutlineCode, HiOutlineCurrencyDollar, HiOutlineEye, HiOutlineVideoCamera, HiOutlineUserGroup, HiOutlineViewBoards, HiOutlineChartBar, HiOutlineClipboardList, HiOutlineTrendingUp, HiOutlineShieldExclamation } from 'react-icons/hi';

export const seekerLinks = [
    { path: '/seeker/dashboard', label: 'Dashboard', icon: <HiOutlineHome /> },
    { section: 'Jobs' },
    { path: '/seeker/browse-jobs', label: 'Browse Jobs', icon: <HiOutlineBriefcase /> },
    { path: '/seeker/my-applications', label: 'My Applications', icon: <HiOutlineDocumentText /> },
    { path: '/seeker/recommended-jobs', label: 'Recommended', icon: <HiOutlineStar /> },
    { path: '/seeker/job-alerts', label: 'Job Alerts', icon: <HiOutlineBell /> },
    { path: '/seeker/saved-jobs', label: 'Saved Jobs', icon: <HiOutlineBookmark /> },
    { section: 'Schedule' },
    { path: '/seeker/interviews', label: 'Interviews', icon: <HiOutlineCalendar /> },
    { path: '/seeker/messages', label: 'Messages', icon: <HiOutlineChatAlt2 /> },
    { section: 'AI Tools' },
    { path: '/seeker/ai-skill-analysis', label: 'Skill Analysis', icon: <HiOutlineLightningBolt /> },
    { path: '/seeker/auto-apply', label: 'Auto Apply', icon: <HiOutlineAdjustments /> },
    { path: '/ai/aptitude-test', label: 'Aptitude Test', icon: <HiOutlineDocumentText /> },
    { section: 'Explore' },
    { path: '/seeker/portfolio', label: 'Portfolio', icon: <HiOutlineCode /> },
    { path: '/seeker/salary-insights', label: 'Salary Insights', icon: <HiOutlineCurrencyDollar /> },
    { path: '/seeker/company-reviews', label: 'Company Reviews', icon: <HiOutlineEye /> },
    { path: '/seeker/video-pitch', label: 'Video Pitch', icon: <HiOutlineVideoCamera /> },
    { section: 'Profile' },
    { path: '/seeker/profile/personal', label: 'My Profile', icon: <HiOutlineUser /> },
    { path: '/seeker/settings', label: 'Settings', icon: <HiOutlineCog /> },
];

export const recruiterLinks = [
    { path: '/recruiter/dashboard', label: 'Dashboard', icon: <HiOutlineHome /> },
    { section: 'Jobs' },
    { path: '/recruiter/post-job', label: 'Post New Job', icon: <HiOutlineBriefcase /> },
    { path: '/recruiter/manage-jobs', label: 'Manage Jobs', icon: <HiOutlineDocumentText /> },
    { path: '/recruiter/applications', label: 'Applications', icon: <HiOutlineStar /> },
    { section: 'Candidates' },
    { path: '/recruiter/candidate-ranking', label: 'Candidate Ranking', icon: <HiOutlineLightningBolt /> },
    { path: '/recruiter/ai-screening', label: 'AI Screening', icon: <HiOutlineAdjustments /> },
    { path: '/recruiter/chat', label: 'Chat', icon: <HiOutlineChatAlt2 /> },
    { path: '/recruiter/bulk-emails', label: 'Bulk Emails', icon: <HiOutlineBell /> },
    { path: '/recruiter/auto-emails', label: 'Auto Emails', icon: <HiOutlineMail /> },
    { path: '/recruiter/aptitude-tests', label: 'Aptitude Tests', icon: <HiOutlineLightningBolt /> },
    { section: 'Manage' },
    { path: '/recruiter/interviews', label: 'Interviews', icon: <HiOutlineCalendar /> },
    { path: '/recruiter/analytics', label: 'Analytics', icon: <HiOutlineDocumentText /> },
    { path: '/recruiter/collaborative', label: 'Collaborative Hiring', icon: <HiOutlineUserGroup /> },
    { path: '/recruiter/kanban', label: 'Kanban Tracker', icon: <HiOutlineViewBoards /> },
    { path: '/recruiter/diversity', label: 'Diversity Metrics', icon: <HiOutlineChartBar /> },
    { path: '/recruiter/rubrics', label: 'Interview Rubrics', icon: <HiOutlineClipboardList /> },
    { path: '/recruiter/company', label: 'Company Profile', icon: <HiOutlineUser /> },
    { path: '/recruiter/subscription', label: 'Subscription', icon: <HiOutlineBookmark /> },
    { path: '/recruiter/account', label: 'Account', icon: <HiOutlineCog /> },
];

export const adminLinks = [
    { path: '/admin/dashboard', label: 'Dashboard', icon: <HiOutlineHome /> },
    { section: 'Users' },
    { path: '/admin/manage-seekers', label: 'Job Seekers', icon: <HiOutlineUser /> },
    { path: '/admin/manage-recruiters', label: 'Recruiters', icon: <HiOutlineBriefcase /> },
    { path: '/admin/block-suspend', label: 'Block/Suspend', icon: <HiOutlineAdjustments /> },
    { section: 'Content' },
    { path: '/admin/manage-jobs', label: 'Job Posts', icon: <HiOutlineDocumentText /> },
    { path: '/admin/activity-logs', label: 'Activity Logs', icon: <HiOutlineCalendar /> },
    { path: '/admin/notifications', label: 'Notifications', icon: <HiOutlineBell /> },
    { section: 'System' },
    { path: '/admin/ai-screening', label: 'AI Settings', icon: <HiOutlineLightningBolt /> },
    { path: '/admin/reports', label: 'Reports', icon: <HiOutlineStar /> },
    { path: '/admin/settings', label: 'System Settings', icon: <HiOutlineCog /> },
    { path: '/admin/backup', label: 'Backup', icon: <HiOutlineDocumentText /> },
    { path: '/admin/admins', label: 'Admin Control', icon: <HiOutlineUser /> },
    { path: '/admin/email-templates', label: 'Email Templates', icon: <HiOutlineChatAlt2 /> },
    { path: '/admin/auto-emails', label: 'Auto Emails', icon: <HiOutlineBell /> },
    { path: '/admin/monitoring', label: 'Monitoring', icon: <HiOutlineBookmark /> },
    { path: '/admin/fraud-detection', label: 'Fraud Detection', icon: <HiOutlineShieldExclamation /> },
    { path: '/admin/revenue', label: 'Revenue Dashboard', icon: <HiOutlineTrendingUp /> },
];
